'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AcademicCalendar

	'''<summary>
	'''btnListView control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnListView As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnCalendarView control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCalendarView As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''lnkAll control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkAll As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkExams control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkExams As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkDeadlines control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkDeadlines As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkRegistration control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkRegistration As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkHolidays control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkHolidays As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkAcademic control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkAcademic As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lblError control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''pnlListView control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlListView As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''litListMonthTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litListMonthTitle As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''rptListEvents control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rptListEvents As Global.System.Web.UI.WebControls.Repeater

	'''<summary>
	'''lblListMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblListMessage As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''pnlCalendarView control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlCalendarView As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''btnPrevMonth control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnPrevMonth As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''litCalendarMonth control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litCalendarMonth As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''litCalendarYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litCalendarYear As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''btnNextMonth control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnNextMonth As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''litCalendar control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litCalendar As Global.System.Web.UI.WebControls.Literal
End Class
